<?php

namespace Database\Seeders;

use App\Models\BrowserVersion;
use Illuminate\Database\Seeder;

class BrowserVersionSeeder extends Seeder
{
    public function run(): void
    {
        $browserVersions = [
            [
                "browser_key" => "Amazon Silk",
                "active" => true,
                "key" => "Amazon Silk/59",
                "name" => "Amazon Silk 59",
            ],
            [
                "browser_key" => "Amazon Silk",
                "active" => true,
                "key" => "Amazon Silk/60",
                "name" => "Amazon Silk 60",
            ],
            [
                "browser_key" => "Amazon Silk",
                "active" => true,
                "key" => "Amazon Silk/63",
                "name" => "Amazon Silk 63",
            ],
            [
                "browser_key" => "Android Browser",
                "active" => true,
                "key" => "Android Browser/-1",
                "name" => "Android Browser -1",
            ],
            [
                "browser_key" => "Android Browser",
                "active" => true,
                "key" => "Android Browser/2",
                "name" => "Android Browser 2",
            ],
            [
                "browser_key" => "Android Browser",
                "active" => true,
                "key" => "Android Browser/3",
                "name" => "Android Browser 3",
            ],
            [
                "browser_key" => "Android Browser",
                "active" => true,
                "key" => "Android Browser/4",
                "name" => "Android Browser 4",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/28",
                "name" => "Chrome Mobile 28.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/29",
                "name" => "Chrome Mobile 29.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/30",
                "name" => "Chrome Mobile 30.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/31",
                "name" => "Chrome Mobile 31.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/32",
                "name" => "Chrome Mobile 32.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/33",
                "name" => "Chrome Mobile 33.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/34",
                "name" => "Chrome Mobile 34.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/35",
                "name" => "Chrome Mobile 35.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/36",
                "name" => "Chrome Mobile 36.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/37",
                "name" => "Chrome Mobile 37.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/38",
                "name" => "Chrome Mobile 38.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/39",
                "name" => "Chrome Mobile 39.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/40",
                "name" => "Chrome Mobile 40.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/41",
                "name" => "Chrome Mobile 41.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/42",
                "name" => "Chrome Mobile 42.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/43",
                "name" => "Chrome Mobile 43.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/44",
                "name" => "Chrome Mobile 44.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/45",
                "name" => "Chrome Mobile 45.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/46",
                "name" => "Chrome Mobile 46.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/47",
                "name" => "Chrome Mobile 47.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/48",
                "name" => "Chrome Mobile 48.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/49",
                "name" => "Chrome Mobile 49.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/50",
                "name" => "Chrome Mobile 50.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/51",
                "name" => "Chrome Mobile 51.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/52",
                "name" => "Chrome Mobile 52.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/53",
                "name" => "Chrome Mobile 53.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/54",
                "name" => "Chrome Mobile 54.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/55",
                "name" => "Chrome Mobile 55.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/56",
                "name" => "Chrome Mobile 56.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/57",
                "name" => "Chrome Mobile 57.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/58",
                "name" => "Chrome Mobile 58.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/59",
                "name" => "Chrome Mobile 59.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/60",
                "name" => "Chrome Mobile 60.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/61",
                "name" => "Chrome Mobile 61.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/62",
                "name" => "Chrome Mobile 62.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/63",
                "name" => "Chrome Mobile 63.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/64",
                "name" => "Chrome Mobile 64.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/65",
                "name" => "Chrome Mobile 65.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/66",
                "name" => "Chrome Mobile 66.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/67",
                "name" => "Chrome Mobile 67.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/68",
                "name" => "Chrome Mobile 68.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/69",
                "name" => "Chrome Mobile 69.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/70",
                "name" => "Chrome Mobile 70.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/71",
                "name" => "Chrome Mobile 71.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/72",
                "name" => "Chrome Mobile 72.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/73",
                "name" => "Chrome Mobile 73.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/74",
                "name" => "Chrome Mobile 74.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/75",
                "name" => "Chrome Mobile 75.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/76",
                "name" => "Chrome Mobile 76.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/77",
                "name" => "Chrome Mobile 77.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/78",
                "name" => "Chrome Mobile 78.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/40",
                "name" => "Chrome 40.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/41",
                "name" => "Chrome 41.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/42",
                "name" => "Chrome 42.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/43",
                "name" => "Chrome 43.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/44",
                "name" => "Chrome 44.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/45",
                "name" => "Chrome 45.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/48",
                "name" => "Chrome 48.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/49",
                "name" => "Chrome 49.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/50",
                "name" => "Chrome 50.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/51",
                "name" => "Chrome 51.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/52",
                "name" => "Chrome 52.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/53",
                "name" => "Chrome 53.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/54",
                "name" => "Chrome 54.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/55",
                "name" => "Chrome 55.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/56",
                "name" => "Chrome 56.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/57",
                "name" => "Chrome 57.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/58",
                "name" => "Chrome 58.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/59",
                "name" => "Chrome 59.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/60",
                "name" => "Chrome 60.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/61",
                "name" => "Chrome 61.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/62",
                "name" => "Chrome 62.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/63",
                "name" => "Chrome 63.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/64",
                "name" => "Chrome 64.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/65",
                "name" => "Chrome 65.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/66",
                "name" => "Chrome 66.x",
            ],
            [
                "browser_key" => "Edge",
                "active" => true,
                "key" => "Edge/12",
                "name" => "Microsoft Edge 12",
            ],
            [
                "browser_key" => "Edge",
                "active" => true,
                "key" => "Edge/13",
                "name" => "Microsoft Edge 13",
            ],
            [
                "browser_key" => "Edge",
                "active" => true,
                "key" => "Edge/14",
                "name" => "Microsoft Edge 14",
            ],
            [
                "browser_key" => "Edge",
                "active" => true,
                "key" => "Edge/15",
                "name" => "Microsoft Edge 15",
            ],
            [
                "browser_key" => "Edge",
                "active" => true,
                "key" => "Edge/16",
                "name" => "Microsoft Edge 16",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/37",
                "name" => "Firefox 37.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/38",
                "name" => "Firefox 38.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/39",
                "name" => "Firefox 39.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/40",
                "name" => "Firefox 40.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/41",
                "name" => "Firefox 41.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/42",
                "name" => "Firefox 42.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/43",
                "name" => "Firefox 43.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/44",
                "name" => "Firefox 44.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/45",
                "name" => "Firefox 45.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/46",
                "name" => "Firefox 46.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/47",
                "name" => "Firefox 47.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/48",
                "name" => "Firefox 48.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/49",
                "name" => "Firefox 49.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/50",
                "name" => "Firefox 50.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/51",
                "name" => "Firefox 51.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/52",
                "name" => "Firefox 52.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/53",
                "name" => "Firefox 53.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/54",
                "name" => "Firefox 54.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/55",
                "name" => "Firefox 55.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/56",
                "name" => "Firefox 56.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/57",
                "name" => "Firefox 57.x",
            ],
            [
                "browser_key" => "Firefox",
                "active" => true,
                "key" => "Firefox/58",
                "name" => "Firefox 58.x",
            ],
            [
                "browser_key" => "Internet Explorer",
                "active" => true,
                "key" => "Internet Explorer/10",
                "name" => "Internet Explorer 10",
            ],
            [
                "browser_key" => "Internet Explorer",
                "active" => true,
                "key" => "Internet Explorer/11",
                "name" => "Internet Explorer 11",
            ],
            [
                "browser_key" => "Internet Explorer",
                "active" => true,
                "key" => "Internet Explorer/8",
                "name" => "Internet Explorer 8",
            ],
            [
                "browser_key" => "Internet Explorer",
                "active" => true,
                "key" => "Internet Explorer/9",
                "name" => "Internet Explorer 9",
            ],
            [
                "browser_key" => "Opera Mini",
                "active" => true,
                "key" => "Opera Mini/28",
                "name" => "Opera Mini 28",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/23",
                "name" => "Opera 23.x",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/24",
                "name" => "Opera 24.x",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/25",
                "name" => "Opera 25.x",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/26",
                "name" => "Opera 26.x",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/27",
                "name" => "Opera 27.x",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/28",
                "name" => "Opera 28.x",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/29",
                "name" => "Opera 29.x",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/30",
                "name" => "Opera 30.x",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/46",
                "name" => "Opera 46",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/47",
                "name" => "Opera 47",
            ],
            [
                "browser_key" => "Opera",
                "active" => true,
                "key" => "Opera/50",
                "name" => "Opera 50",
            ],
            [
                "browser_key" => "Puffin",
                "active" => true,
                "key" => "Puffin/5",
                "name" => "Puffin 5",
            ],
            [
                "browser_key" => "Puffin",
                "active" => true,
                "key" => "Puffin/6",
                "name" => "Puffin 6",
            ],
            [
                "browser_key" => "Safari",
                "active" => true,
                "key" => "Safari/10",
                "name" => "Safari 10",
            ],
            [
                "browser_key" => "Safari",
                "active" => true,
                "key" => "Safari/11",
                "name" => "Safari 11",
            ],
            [
                "browser_key" => "Safari",
                "active" => true,
                "key" => "Safari/5",
                "name" => "Safari 5.x",
            ],
            [
                "browser_key" => "Safari",
                "active" => true,
                "key" => "Safari/6",
                "name" => "Safari 6.x",
            ],
            [
                "browser_key" => "Safari",
                "active" => true,
                "key" => "Safari/7",
                "name" => "Safari 7.x",
            ],
            [
                "browser_key" => "Safari",
                "active" => true,
                "key" => "Safari/8",
                "name" => "Safari 8.x",
            ],
            [
                "browser_key" => "Safari",
                "active" => true,
                "key" => "Safari/9",
                "name" => "Safari 9.x",
            ],
            [
                "browser_key" => "Samsung Browser",
                "active" => true,
                "key" => "Samsung Browser/2",
                "name" => "Samsung Browser 2",
            ],
            [
                "browser_key" => "Samsung Browser",
                "active" => true,
                "key" => "Samsung Browser/3",
                "name" => "Samsung Browser 3",
            ],
            [
                "browser_key" => "Samsung Browser",
                "active" => true,
                "key" => "Samsung Browser/4",
                "name" => "Samsung Browser 4",
            ],
            [
                "browser_key" => "Samsung Browser",
                "active" => true,
                "key" => "Samsung Browser/5",
                "name" => "Samsung Browser 5",
            ],
            [
                "browser_key" => "Samsung Browser",
                "active" => true,
                "key" => "Samsung Browser/6",
                "name" => "Samsung Browser 6",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/79",
                "name" => "Chrome Mobile 79.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/80",
                "name" => "Chrome Mobile 80.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/81",
                "name" => "Chrome Mobile 81.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/82",
                "name" => "Chrome Mobile 82.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/83",
                "name" => "Chrome Mobile 83.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/84",
                "name" => "Chrome Mobile 84.x",
            ],
            [
                "browser_key" => "Chrome Mobile",
                "active" => true,
                "key" => "Chrome Mobile/85",
                "name" => "Chrome Mobile 85.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/67",
                "name" => "Chrome 67.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/68",
                "name" => "Chrome 68.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/69",
                "name" => "Chrome 69.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/70",
                "name" => "Chrome 70.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/71",
                "name" => "Chrome 71.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/72",
                "name" => "Chrome 72.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/73",
                "name" => "Chrome 73.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/74",
                "name" => "Chrome 74.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/75",
                "name" => "Chrome 75.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/76",
                "name" => "Chrome 76.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/77",
                "name" => "Chrome 77.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/78",
                "name" => "Chrome 78.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/79",
                "name" => "Chrome 79.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/80",
                "name" => "Chrome 80.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/81",
                "name" => "Chrome 81.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/82",
                "name" => "Chrome 82.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/83",
                "name" => "Chrome 83.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/84",
                "name" => "Chrome 84.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/85",
                "name" => "Chrome 85.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/86",
                "name" => "Chrome 86.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/87",
                "name" => "Chrome 87.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/88",
                "name" => "Chrome 88.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/89",
                "name" => "Chrome 89.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/90",
                "name" => "Chrome 90.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/91",
                "name" => "Chrome 91.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/92",
                "name" => "Chrome 92.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/93",
                "name" => "Chrome 93.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/94",
                "name" => "Chrome 94.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/95",
                "name" => "Chrome 95.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/96",
                "name" => "Chrome 96.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/97",
                "name" => "Chrome 97.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/98",
                "name" => "Chrome 98.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/99",
                "name" => "Chrome 99.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/100",
                "name" => "Chrome 100.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/101",
                "name" => "Chrome 101.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/102",
                "name" => "Chrome 102.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/103",
                "name" => "Chrome 103.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/104",
                "name" => "Chrome 104.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/105",
                "name" => "Chrome 105.x",
            ],
            [
                "browser_key" => "Chrome",
                "active" => true,
                "key" => "Chrome/106",
                "name" => "Chrome 106.x",
            ],
        ];

        $query = BrowserVersion::query();

        $query->insert($browserVersions);
    }
}
