<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CurrenciesSeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            [
                'id' => Str::uuid()->toString(),
                'key' => 'AED',
                'name' => 'Arab Emirates Dirham',
                'glyph' => 'AED$',
                'emoji_flag' => 'flag-ae',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'ARS',
                'name' => 'Argentine Peso',
                'glyph' => '$',
                'emoji_flag' => ':flag-ar:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'AUD',
                'name' => 'Australian Dollar',
                'glyph' => 'A$',
                'emoji_flag' => ':flag-au:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'BRL',
                'name' => 'Brazilian Real',
                'glyph' => 'R$',
                'emoji_flag' => ':flag-br:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'CAD',
                'name' => 'Canadian Dollar',
                'glyph' => 'C$',
                'emoji_flag' => ':flag-ca:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'CHF',
                'name' => 'Swiss Franc',
                'glyph' => 'CH',
                'emoji_flag' => ':flag-ch:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'CLP',
                'name' => 'Chilean Peso',
                'glyph' => 'CLP$',
                'emoji_flag' => ':flag-cl:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'COP',
                'name' => 'Colombian Peso',
                'glyph' => 'COP$',
                'emoji_flag' => ':flag-co:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'EUR',
                'name' => 'Euro',
                'glyph' => '€',
                'emoji_flag' => ':flag-eu:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'GBP',
                'name' => 'Great British Pound',
                'glyph' => '£',
                'emoji_flag' => ':flag-gb:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'HKD',
                'name' => 'Hong Kong Dollar',
                'glyph' => 'HK$',
                'emoji_flag' => ':flag-hk:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'IDR',
                'name' => 'Indonesian Rupiah',
                'glyph' => 'Rp',
                'emoji_flag' => ':flag-id:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'INR',
                'name' => 'Indian Rupee',
                'glyph' => '',
                'emoji_flag' => ':flag-in:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'JPY',
                'name' => 'Japanese Yen',
                'glyph' => '¥',
                'emoji_flag' => ':flag-jp:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'KRW',
                'name' => 'South Korean Won',
                'glyph' => '₩',
                'emoji_flag' => ':flag-kr:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'MXN',
                'name' => 'Mexican Peso',
                'glyph' => 'MEX$',
                'emoji_flag' => ':flag-mx:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'MYR',
                'name' => 'Malaysian Ringgit',
                'glyph' => 'RM',
                'emoji_flag' => ':flag-my:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'NZD',
                'name' => 'New Zealand Dollar',
                'glyph' => '$',
                'emoji_flag' => ':flag-nz:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'PEN',
                'name' => 'Peruvian Sol',
                'glyph' => 'S/',
                'emoji_flag' => ':flag-pe:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'PHP',
                'name' => 'Philippine Peso',
                'glyph' => '₱',
                'emoji_flag' => ':flag-ph:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'PLN',
                'name' => 'Polish Złoty',
                'glyph' => 'zł',
                'emoji_flag' => ':flag-pl:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'RUB',
                'name' => 'Russian Ruble',
                'glyph' => '₽',
                'emoji_flag' => ':flag-ru:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'SEK',
                'name' => 'Swedish Krona',
                'glyph' => 'KR',
                'emoji_flag' => ':flag-se:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'SGD',
                'name' => 'Singapore Dollar',
                'glyph' => 'S$',
                'emoji_flag' => ':flag-sg:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'THB',
                'name' => 'Thai Baht',
                'glyph' => '฿',
                'emoji_flag' => ':flag-th:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'TRY',
                'name' => 'Turkish Lira',
                'glyph' => '₺',
                'emoji_flag' => ':flag-tr:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'UAH',
                'name' => 'Ukrainian Hryvnia',
                'glyph' => '₴',
                'emoji_flag' => ':flag-ua:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'USD',
                'name' => 'United States Dollar',
                'glyph' => '$',
                'emoji_flag' => ':flag-us:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'VND',
                'name' => 'Vietnamese Dong',
                'glyph' => '₫',
                'emoji_flag' => ':flag-vn:',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        $query = Currency::query();

        $query->insert($currencies);
    }
}
