<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $data = [
            [
                "key" => "-1",
                "name" => "Unknown",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "aa",
                "name" => "Afar",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ab",
                "name" => "Abkhazian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "af",
                "name" => "Afrikaans",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "am",
                "name" => "Amharic",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ar",
                "name" => "Arabic",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "as",
                "name" => "Assamese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ay",
                "name" => "Aymara",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "az",
                "name" => "Azerbaijani",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ba",
                "name" => "Bashkir",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "be",
                "name" => "Byelorussian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "bg",
                "name" => "Bulgarian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "bh",
                "name" => "Bihari",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "bi",
                "name" => "Bislama",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "bn",
                "name" => "Bengali/Bangla",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "bo",
                "name" => "Tibetan",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "br",
                "name" => "Breton",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ca",
                "name" => "Catalan",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "co",
                "name" => "Corsican",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "cs",
                "name" => "Czech",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "cy",
                "name" => "Welsh",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "da",
                "name" => "Danish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "de",
                "name" => "German",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "dz",
                "name" => "Bhutani",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "el",
                "name" => "Greek",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "en",
                "name" => "English",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "eo",
                "name" => "Esperanto",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "es",
                "name" => "Spanish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "et",
                "name" => "Estonian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "eu",
                "name" => "Basque",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "fa",
                "name" => "Persian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "fi",
                "name" => "Finnish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "fj",
                "name" => "Fiji",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "fo",
                "name" => "Faeroese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "fr",
                "name" => "French",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "fy",
                "name" => "Frisian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ga",
                "name" => "Irish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "gd",
                "name" => "Scots/Gaelic",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "gl",
                "name" => "Galician",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "gn",
                "name" => "Guarani",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "gu",
                "name" => "Gujarati",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ha",
                "name" => "Hausa",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "hi",
                "name" => "Hindi",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "hr",
                "name" => "Croatian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "hu",
                "name" => "Hungarian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "hy",
                "name" => "Armenian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ia",
                "name" => "Interlingua",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ie",
                "name" => "Interlingue",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ik",
                "name" => "Inupiak",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "in",
                "name" => "Indonesian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "is",
                "name" => "Icelandic",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "it",
                "name" => "Italian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "iw",
                "name" => "Hebrew",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ja",
                "name" => "Japanese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ji",
                "name" => "Yiddish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "jw",
                "name" => "Javanese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ka",
                "name" => "Georgian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "kk",
                "name" => "Kazakh",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "kl",
                "name" => "Greenlandic",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "km",
                "name" => "Cambodian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "kn",
                "name" => "Kannada",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ko",
                "name" => "Korean",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ks",
                "name" => "Kashmiri",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ku",
                "name" => "Kurdish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ky",
                "name" => "Kirghiz",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "la",
                "name" => "Latin",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ln",
                "name" => "Lingala",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "lo",
                "name" => "Laothian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "lt",
                "name" => "Lithuanian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "lv",
                "name" => "Latvian/Lettish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "mg",
                "name" => "Malagasy",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "mi",
                "name" => "Maori",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "mk",
                "name" => "Macedonian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ml",
                "name" => "Malayalam",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "mn",
                "name" => "Mongolian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "mo",
                "name" => "Moldavian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "mr",
                "name" => "Marathi",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ms",
                "name" => "Malay",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "mt",
                "name" => "Maltese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "my",
                "name" => "Burmese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "na",
                "name" => "Nauru",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ne",
                "name" => "Nepali",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "nl",
                "name" => "Dutch",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "no",
                "name" => "Norwegian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "oc",
                "name" => "Occitan",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "om",
                "name" => "(Afan)/Oromoor/Oriya",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "pa",
                "name" => "Punjabi",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "pl",
                "name" => "Polish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ps",
                "name" => "Pashto/Pushto",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "pt",
                "name" => "Portuguese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "qu",
                "name" => "Quechua",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "rm",
                "name" => "Rhaeto-Romance",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "rn",
                "name" => "Kirundi",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ro",
                "name" => "Romanian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ru",
                "name" => "Russian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "rw",
                "name" => "Kinyarwanda",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sa",
                "name" => "Sanskrit",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sd",
                "name" => "Sindhi",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sg",
                "name" => "Sangro",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sh",
                "name" => "Serbo-Croatian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "si",
                "name" => "Singhalese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sk",
                "name" => "Slovak",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sl",
                "name" => "Slovenian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sm",
                "name" => "Samoan",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sn",
                "name" => "Shona",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "so",
                "name" => "Somali",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sq",
                "name" => "Albanian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sr",
                "name" => "Serbian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ss",
                "name" => "Siswati",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "st",
                "name" => "Sesotho",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "su",
                "name" => "Sundanese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sv",
                "name" => "Swedish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "sw",
                "name" => "Swahili",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ta",
                "name" => "Tamil",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "te",
                "name" => "Tegulu",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "tg",
                "name" => "Tajik",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "th",
                "name" => "Thai",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ti",
                "name" => "Tigrinya",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "tk",
                "name" => "Turkmen",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "tl",
                "name" => "Tagalog",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "tn",
                "name" => "Setswana",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "to",
                "name" => "Tonga",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "tr",
                "name" => "Turkish",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ts",
                "name" => "Tsonga",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "tt",
                "name" => "Tatar",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "tw",
                "name" => "Twi",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "uk",
                "name" => "Ukrainian",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "ur",
                "name" => "Urdu",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "uz",
                "name" => "Uzbek",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "vi",
                "name" => "Vietnamese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "vo",
                "name" => "Volapuk",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "wo",
                "name" => "Wolof",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "xh",
                "name" => "Xhosa",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "yo",
                "name" => "Yoruba",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "zh",
                "name" => "Chinese",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "key" => "zu",
                "name" => "Zulu",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ]
        ];

        Language::insert($data);
    }
}
