<?php

namespace Database\Seeders;

use App\Models\ListModel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ListsSeeder extends Seeder
{
    public function run(): void
    {
        $lists = [
            [
                "original_id" => 141,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Honda Johnstown Zip Codes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 228,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "TTU_Admin_Sports_BundleBlockList",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 226,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Sample Domain List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 225,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Test List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 192,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Global_PX_Bundle_Blocklist",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 224,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "test",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 194,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Boardman (Only)_Lat_Long",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 40,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 222,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Greenburgh_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 221,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "FordBoardman_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 220,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "BeaverCounty_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 216,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Warrendale_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 217,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "FoxChapel_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 218,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Robinson_ZipCodeListt",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 219,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Sewickley_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 215,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "SevenFields_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 120,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "TTU_Domain_Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 149,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Honda_Domain_Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 178,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "LGKG Domain Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 124,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "MASTER_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 72,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "TTU CTV Block List",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 213,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Greentree_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 211,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Wexford_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 212,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Kennedy_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 209,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "NorthHills_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 210,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Bridgeville_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 208,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Pittsburgh_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 205,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Moon_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 206,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "South Hills_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 201,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Bethel Park_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 202,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cranberry_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 203,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Butler_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 204,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Hopewell_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 200,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Mt. Lebanon_ZipcodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 199,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Monroeville_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 197,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "BlairsvillePA_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 198,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Murrysville_ZipCode_List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 196,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "AK Valley_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 195,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "PennHills_ZipCodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 70,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "PilotX_535_Approved_BundleIDList",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 122,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Master_PX_Domain_List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 184,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran Ford Zipcodes_3Stores_25mRadius",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 193,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "DiscoveryPlus_BundleBlockList",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 123,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Master_PX_Approved_BundleIDList",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 188,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Westmoreland County Zip Code List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 189,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Allegheny County Zip Code List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 187,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Max_BundleList",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 185,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran Subaru Zipcodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 186,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "LGKG Zipcodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 183,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran CDJR Zipcodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 181,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran CDJR Domain Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 179,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran CDJR App Blocklist",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 180,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran Ford App Blocklist",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 176,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "LGKG App Blocklist",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 175,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "UC Entertainment App Blocklist",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 182,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran Ford Domain Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 177,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "UC Entertainment Domain Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 174,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran Subaru Geo Targeting",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 40,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 173,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "LGKG Lat/Long",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 40,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 172,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran CDJR Lat/Long",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 40,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 171,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran Nissan PreRoll Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 169,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "PX_OTT_DealID_List",
                "type" => "deal_id",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 170,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "PX_Desktop_Video_Deal_List",
                "type" => "deal_id",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 168,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Mazda_ZipCodes(July2023)",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 167,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran Nissan GeoTargeting",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 40,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 166,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "LGKG_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 164,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Pittsburgh 40 mi radius",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 50,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 162,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Harrington_ZipCode_List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 160,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_PromoCorp_Domain_Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 159,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Pittsburgh_Bundle_Blocklist",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 158,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Monroeville_Bundle_Blocklist",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 156,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Sports_Domains_List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 157,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Desktop_Sports",
                "type" => "deal_id",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 155,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Sports_Bundle_List",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 154,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Hyundai_Pittsburgh_LatLong",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 40,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 153,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Hyundai_Monroeville_LatLong",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 40,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 148,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Ford_Domain_Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 146,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Ford_ZipCodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 115,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Mazda_ZipCodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 145,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Butler County ZipCode List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 144,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Subaru PreRoll Domain Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 143,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Honda_Domains_Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 73,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "535_Approved_DomainList",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 139,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Pittsburgh DMA Zip Code List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 140,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Johnstown PA Zip Code List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 138,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Monroeville PA Zip Codes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 137,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "CBS News/Sports WL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 136,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "CBS News Bundle WL",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 113,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ColumbiaGas_York_PreRoll_BL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 114,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ColumbiaGas_PGH_PreRoll_BL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 135,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cambria_ZipCode_List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 134,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Somerset_ZipCode_List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 133,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Bedford_ZipCode_List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 132,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Altoona_ZipCode_List",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 131,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Domain_BlockList",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 83,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Local_Pittsburgh_BundleIDs_WL",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 129,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ColGas_Domain_Blocklist",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 125,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Ford_ZipCodeList",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 121,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Ford_LatLong_LIst",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 16.09,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 119,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "PilotX_TTU_Domain_List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 118,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_CarStock_Domain_BlockList",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 117,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Knisely & Sons PreRoll BL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 116,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Armstrong, Clarion, Indiana, Shelocta, PA",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 105,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Miss_Utility_Targeted_App/Bundle_BL",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 101,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "MissUtility_Targeted_Domains_BL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 104,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Miss_Utility_GeoFence_App/Bundle_BL",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 96,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "MissUtility_GeoFence_Domains_BL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 103,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Local_Morgantown_Domain_List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 102,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "MissUtility_Targeted_WL_Domains",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 95,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "MissUtility_GeoFence_ZipCodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 97,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Pluto_BundleID_List",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 93,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ColumbiaGas_StateCollege",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 94,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ColumbiaGas_BradfordWarren",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 91,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ColumbiaGas_York_ZipCodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 92,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ColumbiaGas_Gettysburg",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 90,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ColumbiaGas_PittZipCodes",
                "type" => "zip_code",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 88,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "WPXI Domain List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 67,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "App Bundle Block List",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 87,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "ReduceTraffic_DomainList_TribLive",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 86,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Spotify_DealID_List",
                "type" => "deal_id",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 85,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "DO NOT USE",
                "type" => "deal_id",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 84,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Local_Pittsburgh_Domains_WL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 71,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Domain_Block_List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 82,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_PreRoll_Bundle_Block List",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 81,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran_Morgantown_Deal List",
                "type" => "deal_id",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 80,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "WTAJ_Domain_List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 79,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "WTAJ App Bundle List",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 69,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Brentwood Bank HELOC Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 68,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Domain Desktop_MW Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 34,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Cochran Block List",
                "type" => "app_bundle",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 35,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "iCube Nashville WL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 36,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "iCube Memphis WL",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 33,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "icube Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 29,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "California University of PA Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 30,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Columbia Gas: Count on Columbia Lat/Long List",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 2,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 12,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Columbia Gas: Count on Columbia Lat/Long Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 13,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Columbia Gas: Count on Columbia Keyword Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 28,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "University of Pitts Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 27,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "LIVE Casino Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 26,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Tennessee Tech Preview Day Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 9,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "BB Kasasa Union Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 11,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "BB Love Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 19,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "LIVE! Casino Lat/Long",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 1,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 18,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "LIVE Casino Contextual Geo",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 48,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 10,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "BB Kasasa South Hills Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 5,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Columbia Gas: Count on Columbia",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 2,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 7,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Tri State Office Furniture: Safe Office Solutions",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 0.5,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 16,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Tri State Safe Office Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 4,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Brentwood Bank: Love",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 0.5,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 14,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "TTU Engineering Lat/Long Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 15,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "TTU President's Summer Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 8,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "TTU Engineering Keyword Block List",
                "type" => "domain",
                "attributes" => null,
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                "original_id" => 6,
                "active" => true,
                "alternative_id" => null,
                "notes" => null,
                "name" => "Tennessee Tech: Engineering Graduate Program",
                "type" => "lat_long",
                "attributes" => json_encode([
                    "default_radius_km" => 3,
                ]),
                "upload_type" => "DIRECT_UPLOAD",
                "delimiter" => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        $query = ListModel::query();

        $query->insert($lists);
    }
}

