<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\OperatingSystemVersion;

class OperatingSystemVersionSeeder extends Seeder
{
    public function run(): void
    {
        $versions = [
            [
                "operating_system_key" => "-1",
                "active" => true,
                "key" => "-1",
                "name" => "Unknown",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/10.0",
                "name" => "Android 10 (10.0)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/2.1",
                "name" => "Android Eclair (2.0)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/2.2",
                "name" => "Android Froyo (2.2)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/2.3",
                "name" => "Android Gingerbread (2.3)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/3.0",
                "name" => "Android Honeycomb (3.0)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/3.1",
                "name" => "Android Honeycomb (3.1)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/3.2",
                "name" => "Android Honeycomb (3.2)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/4.0",
                "name" => "Android Ice Cream Sandwich (4.0.1)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/4.1",
                "name" => "Android Jelly Bean (4.1)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/4.2",
                "name" => "Android Jelly Bean (4.2)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/4.3",
                "name" => "Android Jelly Bean (4.3)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/4.4",
                "name" => "Android KitKat (4.4)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/5.0",
                "name" => "Android Lollipop (5.0)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/5.1",
                "name" => "Android Lollipop (5.1)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/6.0",
                "name" => "Android Marshmallow (6.0)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/7.0",
                "name" => "Android Nougat (7.0)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/7.1",
                "name" => "Android Nougat (7.1)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/8.0",
                "name" => "Android Oreo (8.0)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/8.1",
                "name" => "Android Oreo (8.1)",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/9.0",
                "name" => "Android Pie (9.0)",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/10",
                "name" => "iOS 10",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/11",
                "name" => "iOS 11",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/12",
                "name" => "iOS 12",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/13",
                "name" => "iOS 13",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/6",
                "name" => "iOS 6",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/7",
                "name" => "iOS 7",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/8",
                "name" => "iOS 8",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/9",
                "name" => "iOS 9",
            ],
            [
                "operating_system_key" => "Linux",
                "active" => true,
                "key" => "Linux/Fedora",
                "name" => "Linux Fedora",
            ],
            [
                "operating_system_key" => "Linux",
                "active" => true,
                "key" => "Linux/Mint",
                "name" => "Linux Mint",
            ],
            [
                "operating_system_key" => "Linux",
                "active" => true,
                "key" => "Linux/openSUSE",
                "name" => "Linux openSUSE",
            ],
            [
                "operating_system_key" => "Linux",
                "active" => true,
                "key" => "Linux/Red Hat",
                "name" => "Linux Red Hat",
            ],
            [
                "operating_system_key" => "Linux",
                "active" => true,
                "key" => "Linux/Slackware",
                "name" => "Linux Slackware",
            ],
            [
                "operating_system_key" => "Linux",
                "active" => true,
                "key" => "Linux/Ubuntu",
                "name" => "Linux Ubuntu",
            ],
            [
                "operating_system_key" => "OS X",
                "active" => true,
                "key" => "OS X/10.10",
                "name" => "OSX Yosemite",
            ],
            [
                "operating_system_key" => "OS X",
                "active" => true,
                "key" => "OS X/10.11",
                "name" => "OSX El Capitan",
            ],
            [
                "operating_system_key" => "OSX",
                "active" => true,
                "key" => "OS X/10.12",
                "name" => "OSX Sierra",
            ],
            [
                "operating_system_key" => "OSX",
                "active" => true,
                "key" => "OS X/10.13",
                "name" => "OSX High Sierra",
            ],
            [
                "operating_system_key" => "OS X",
                "active" => true,
                "key" => "OS X/10.7",
                "name" => "OSX Lion",
            ],
            [
                "operating_system_key" => "OS X",
                "active" => true,
                "key" => "OS X/10.8",
                "name" => "OSX Mountain Lion",
            ],
            [
                "operating_system_key" => "OS X",
                "active" => true,
                "key" => "OS X/10.9",
                "name" => "OSX Mavericks",
            ],
            [
                "operating_system_key" => "OSX",
                "active" => true,
                "key" => "OSX/10.5",
                "name" => "OSX Leopard",
            ],
            [
                "operating_system_key" => "OSX",
                "active" => true,
                "key" => "OSX/10.6",
                "name" => "OSX Snow Leopard",
            ],
            [
                "operating_system_key" => "PlayStation OS",
                "active" => true,
                "key" => "PlayStation OS/3",
                "name" => "PlayStation OS 3",
            ],
            [
                "operating_system_key" => "PlayStation OS",
                "active" => true,
                "key" => "PlayStation OS/4",
                "name" => "PlayStation OS 4",
            ],
            [
                "operating_system_key" => "RIM",
                "active" => true,
                "key" => "RIM/BB10",
                "name" => "BB10",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/10.0",
                "name" => "tvOS 10.0",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/10.1",
                "name" => "tvOS 10.1",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/10.2",
                "name" => "tvOS 10.2",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/11.0",
                "name" => "tvOS 11.0",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/11.1",
                "name" => "tvOS 11.1",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/11.2",
                "name" => "tvOS 11.2",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/11.3",
                "name" => "tvOS 11.3",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/11.4",
                "name" => "tvOS 11.4",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/12.0",
                "name" => "tvOS 12.0",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/12.1",
                "name" => "tvOS 12.1",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/12.2",
                "name" => "tvOS 12.2",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/12.3",
                "name" => "tvOS 12.3",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/12.4",
                "name" => "tvOS 12.4",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/9.0",
                "name" => "tvOS 9.0",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/9.1",
                "name" => "tvOS 9.1",
            ],
            [
                "operating_system_key" => "tvOS",
                "active" => true,
                "key" => "tvOS/9.2",
                "name" => "tvOS 9.2",
            ],
            [
                "operating_system_key" => "Windows Phone",
                "active" => true,
                "key" => "Windows Phone/10.0",
                "name" => "Windows Phone 10.0",
            ],
            [
                "operating_system_key" => "Windows Phone",
                "active" => true,
                "key" => "Windows Phone/7.0",
                "name" => "Windows Phone 7.0",
            ],
            [
                "operating_system_key" => "Windows Phone",
                "active" => true,
                "key" => "Windows Phone/8.0",
                "name" => "Windows Phone 8.0",
            ],
            [
                "operating_system_key" => "Windows",
                "active" => true,
                "key" => "Windows/10",
                "name" => "Windows10",
            ],
            [
                "operating_system_key" => "Windows",
                "active" => true,
                "key" => "Windows/7",
                "name" => "Windows7",
            ],
            [
                "operating_system_key" => "Windows",
                "active" => true,
                "key" => "Windows/8",
                "name" => "Windows8",
            ],
            [
                "operating_system_key" => "Windows",
                "active" => true,
                "key" => "Windows/8.1",
                "name" => "Windows8.1",
            ],
            [
                "operating_system_key" => "Windows",
                "active" => true,
                "key" => "Windows/RT",
                "name" => "WindowsRT",
            ],
            [
                "operating_system_key" => "Windows",
                "active" => true,
                "key" => "Windows/Vista",
                "name" => "WindowsVista",
            ],
            [
                "operating_system_key" => "Windows",
                "active" => true,
                "key" => "Windows/XP",
                "name" => "WindowsXP",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/14",
                "name" => "iOS 14",
            ],
            [
                "operating_system_key" => "Android",
                "active" => true,
                "key" => "Android/11.0",
                "name" => "Android 11 (11.0)",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/3.0",
                "name" => "webOS 3.0",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/3.5",
                "name" => "webOS 3.5",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/4.0",
                "name" => "webOS 4.0",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/4.5",
                "name" => "webOS 4.5",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/5.0",
                "name" => "webOS 5.0",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/6.0",
                "name" => "webOS 6.0",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/15",
                "name" => "iOS 15",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/22",
                "name" => "webOS 22",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/23",
                "name" => "webOS 23",
            ],
            [
                "operating_system_key" => "iOS",
                "active" => true,
                "key" => "iOS/16",
                "name" => "iOS 16",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/24",
                "name" => "webOS 24",
            ],
            [
                "operating_system_key" => "webOS",
                "active" => true,
                "key" => "webOS/25",
                "name" => "webOS 25",
            ],
        ];

        $query = OperatingSystemVersion::query();

        $query->insert($versions);
    }
}
